name: HOT Claim
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/70 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: wget https://cheatgame.pro/education/dataairdrop/datahot.txt; python hot_claim.py
